config/routes.rb
def api_version_helper(version, mime, &block)
  version_str = "v#{version}"
  api_version module: version_str,
              path: { value: version_str },
              parameter: { name: :apiVersion, value: version_str },
              &block
  scope as: :header do
    api_version module: version_str, header: { name: :Accept, value: "#{mime};version=#{version}" }, &block
  end
end

Rails.application.routes.draw do
  controller :wiki, path: :wiki do
    get '/', action: :index, as: :wiki_index
    get ':page', action: :show, as: :wiki, page: %r{[^/]+}
  end

  controller :profile, path: :user do
    get '(:username)', action: :show, as: :profile
    get '(:username)/feed' => 'feed#user', as: :feed_profile
    get '(:username)/files', action: :files, as: :profile_files
    get '(:username)/versions', action: :versions, as: :profile_versions
    get '(:username)/brief_feed' => 'feed#brief_user', as: :brief_feed_profile
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    scope path: 'users' do
      match 'finish_signup' => 'users/registrations#finish_signup', via: [:get, :patch, :post], as: :finish_signup
      get 'accounts' => 'users/registrations#accounts', as: :user_accounts
      get 'auth/:provider/destroy' => 'users/omniauth_callbacks#destroy', as: :omniauth_unlink
      match 'reset_authentication_token' => 'users/registrations#reset_authentication_token',
            via: [:get, :patch, :post], as: :reset_authentication_token

      resources :uploaders do
        member do
          match 'reset_token', via: [:get, :patch, :post]
        end
      end
    end
  end

  authenticate :user, ->(user) { user.admin } do
    mount DjMon::Engine => 'dj_mon'
  end

  post 'upload_version' => 'wonko_versions#upload'

  resources :wonko_files, id: %r{[^/]+} do
    member do
      get 'feed' => 'feed#file'
      scope controller: 'wonko_files_transfer' do
        get 'transfer'
        post 'transfer'
        get 'accept_transfer'
        get 'reject_transfer'
        get 'cancel_transfer'
      end
    end

    resources :wonko_versions, id: %r{[^/]+} do
      member do
        get 'copy'
        get 'feed' => 'feed#version'
      end
    end
  end

  root 'home#index'
  get 'about' => 'home#about'
  get 'irc' => 'home#irc'

  namespace :api,
            format: true,
            constraints: { format: :json },
            defaults: { format: :json },
            wonko_file_id: %r{[^/]+},
            id: %r{[^/]+} do
    api_version_helper 1, 'application/wonkoweb-api' do
      scope controller: 'wonko_files' do
        root action: :index
        get 'index', action: :index, as: :index
        get ':id', action: :show, as: :file
        post action: :create, as: :create_file
        patch ':id', action: :update
      end
      scope path: ':wonko_file_id', controller: 'wonko_versions' do
        get ':id', action: :show, as: :version
        post action: :create, as: :create_version
        patch ':id', action: :update
      end
    end
  end

end

app/models/wonko_version.rb
# == Schema Information
#
# Table name: wonko_versions
#
#  id            :integer          not null, primary key
#  version       :string
#  type          :string
#  time          :string
#  origin        :string
#  user_id       :integer
#  wonko_file_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_wonko_versions_on_user_id                                (user_id)
#  index_wonko_versions_on_version                                (version)
#  index_wonko_versions_on_wonko_file_id                          (wonko_file_id)
#  index_wonko_versions_on_wonko_file_id_and_user_id_and_version  (wonko_file_id,user_id,version) UNIQUE
#

class WonkoVersion < ActiveRecord::Base
  self.inheritance_column = nil

  include PublicActivity::Model
  tracked owner: proc { |controller, _model| controller ? controller.current_user : nil }, recipient: :wonko_file,
          parameters: proc { |_, m| { uid: m.uid, version: m.version } }

  attr_readonly :version

  belongs_to :wonko_file, class_name: :WonkoFile, inverse_of: :wonkoversions
  belongs_to :user
  has_one :origin, class_name: :WonkoOrigin, as: :object

  paginates_per 50

  validates :version,
            presence: true,
            length: { minimum: 1 },
            uniqueness: { scope: [:wonko_file_id, :user_id], message: 'already exists' }
  validates :user, presence: true
  validates :origin, presence: true

  delegate :uid, to: :wonko_file

  def requires
    JSON.parse(KVStorageInterface.get("#{uid}##{version}#requires") || '[]')
  end

  def requires=(data)
    KVStorageInterface.set "#{uid}##{version}#requires", (data || []).to_json
  end

  def data
    JSON.parse(KVStorageInterface.get("#{uid}##{version}") || '[]')
  end

  def data=(data)
    KVStorageInterface.set "#{uid}##{version}", (data || []).to_json
  end

  scope :related_to, ->(user) do
    joins(:wonko_file).where('wonko_versions.user_id = :user OR wonko_files.user_id = :user', user: user)
  end

  def to_param
    version
  end

  def time_as_string
    time.nil? ? '' : Time.zone.at(time.to_i).to_datetime.strftime('%Y-%m-%d %H:%M:%S')
  end

  def self.get(file, id, user = nil)
    if user
      file.wonkoversions.where(user: user).find_by(version: id)
    else
      file.wonkoversions.find_by(version: id)
    end
  rescue ActiveRecord::RecordNotFound
    return nil
  end

  def self.find_or_create_for_data(file, data, user)
    wonko_version = file.wonkoversions.find_or_initialize_by(version: data[:version], user: user)

    wonko_version.data = data[:data]
    # wonko_version.requires = data[:requires] || []
    wonko_version.user = user
    wonko_version.update_attributes data.permit(:version, :type, :time)
    wonko_version
  end
end

app/controllers/api/v1/wonko_versions_controller.rb
module Api
  module V1
    class WonkoVersionsController < Api::ApiController
      before_action :set_wonko_file
      before_action :set_wonko_version, only: [:show, :update]
      before_action :authenticate_user!, except: [:index, :show]
      wrap_parameters :wonko_version, include: [:version, :type, :time, :requires, :data]

      def show
        authorize @wonko_version
        fresh_when @wonko_version, template: 'show'
      end

      def create
        @wonko_version = @wonko_file.wonkoversions.new
        @wonko_version.assign_attributes params.require(:wonko_version).permit(:version, :type, :time)
        @wonko_version.data = params.require(:wonko_version)[:data]
        @wonko_version.requires = params.require(:wonko_version)[:requires]
        @wonko_version.user = current_user
        WonkoOrigin.assign(@wonko_version, self, 'api')
        authorize @wonko_version

        if @wonko_version.save
          render 'show', status: :created if stale? @wonko_version, template: 'show'
        else
          render_json_errors @wonko_version.errors
        end
      rescue ActionController::ParameterMissing, ActionController::UnpermittedParameters
        render_json_errors bad_request: { title: 'Wrong parameters (allowed: version, type, time, requires, data)',
                                          status: :bad_request }
      end

      def update
        @wonko_version.assign_attributes params.require(:wonko_version).permit(:type, :time)
        @wonko_version.data = params.require(:wonko_version)[:data]
        @wonko_version.requires = params.require(:wonko_version)[:requires]
        authorize @wonko_version

        if @wonko_version.save
          render 'show', status: :ok if stale? @wonko_version, template: 'show'
        else
          render_json_errors @wonko_version.errors
        end
      end
    end
  end
end

app/controllers/wonko_versions_controller.rb
class WonkoVersionsController < ApplicationController
  before_action :files_crumb
  before_action :set_wonko_file, except: [:upload]
  before_action :set_wonko_version, only: [:show, :edit, :update, :destroy, :copy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @wonko_versions = scope_collection @wonko_file.wonkoversions.order time: :desc
    authorize @wonko_versions
  end

  def show
    authorize @wonko_version
  end

  def new
    @wonko_version = @wonko_file.wonkoversions.build
    @wonko_version.user = current_user
    authorize @wonko_version
    versions_crumb
    add_breadcrumb 'New', route(:new, @wonko_version)
  end

  def edit
    authorize @wonko_version
    add_breadcrumb 'Edit', route(:edit, @wonko_version)
  end

  def create
    @wonko_version = @wonko_file.wonkoversions.build(wonko_version_params)
    @wonko_version.user = current_user
    WonkoOrigin.assign @wonko_version, self, 'created_from_web'
    do_respond_to :create?, 'created', @wonko_version.save, :new
  end

  def upload
    files = params[:file].is_a?(Array) ? params[:file] : [params[:file]]
    results = []

    files.each do |file|
      data = ActionController::Parameters.new(JSON.parse file.read)
      file = WonkoFile.find_by(uid: data[:uid])

      @wonko_version = WonkoVersion.find_or_create_for_data file, data, current_user
      WonkoOrigin.assign @wonko_version, self, 'uploaded_from_web'
      is_new = @wonko_version.new_record?
      authorize @wonko_version, (is_new ? :update? : :create?)

      if @wonko_version.save
        results << @wonko_version
      else
        render :new
        break
      end
    end

    return if response_body

    if results.size == 1
      redirect_to route(:show, results.first, user: results.first.user.username),
                  notice: 'Wonko version was successfully created.'
    else
      redirect_to root_path, notice: 'Wonko versions were successfully created.'
    end
  end

  def update
    do_respond_to :update?, 'updated',
                  !wonko_version_params.empty? && @wonko_version.update(wonko_version_params), :edit
  end

  def destroy
    authorize @wonko_version
    @wonko_version.delete
    redirect_to route(:index, @wonko_file, WonkoVersion),
                notice: 'Wonko version was successfully destroyed.'
  end

  def copy
    authorize @wonko_version, :show?

    unless view_context.can_copy(@wonko_version)
      redirect_to route(:show, @wonko_version, user: current_user.username),
                  notice: 'You already have this version'
      return
    end

    origin = @wonko_version.origin
    @wonko_version = @wonko_version.dup
    @wonko_version.user = current_user
    @wonko_version.origin = origin.dup
    do_respond_to :create?, 'copied', @wonko_version.save, :new
  end

  private

  def do_respond_to(action, verb, success, error_redirect)
    @wonko_version.user = current_user
    authorize @wonko_version, action

    if success
      redirect_to route(:show, @wonko_version, user: current_user.username),
                  notice: "Wonko version was successfully #{verb}."
    else
      render error_redirect
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wonko_version_params
    params.require(:wonko_version).permit(:version, :type, :time, :requires, :data)
  end
end

app/helpers/wonko_versions_helper.rb
module WonkoVersionsHelper
  def can_copy(version)
    policy(version).show? && policy(WonkoVersion).create? &&
      version.wonko_file.wonkoversions.where(user: current_user, version: version.version).empty?
  end

  def own(version)
    WonkoVersion.get(version.wonko_file, version.version, current_user)
  end

  def show_go_to_mine(version)
    current_user && !own(version).nil? && version.user != current_user
  end
end

app/views/wonko_versions/_form.html.slim
= simple_form_for @wonko_version, url: form_route(@wonko_version) do |f|
  - if @wonko_version.new_record?
    = f.input :version
  = f.input :type
  = f.input :time, wrapper: :vertical_input_group
    span.input-group-addon#humanTime
    = f.input_field :time, class: 'form-control'
    span.input-group-btn
      = bootstrap_button_to 'Now', 'javascript:time_now();', :default
  / TODO: use http://www.malot.fr/bootstrap-datetimepicker/
  = f.button :submit, 'Save'

javascript:
  function updateHumanTime() {
    $('#humanTime').html((new Date(parseInt($('#wonko_version_time').val()) * 1000)).toString());
  }
  function time_now() {
    updateHumanTime();
    $('#wonko_version_time').val(Math.floor(Date.now() / 1000));
  }
  updateHumanTime();
  $('#wonko_version_time').on('change keyup keydown', updateHumanTime);

app/views/wonko_versions/_table.html.slim
= page_entries_info @wonko_versions, entry_name: 'version'
table.table
  thead
    tr
      th Version
      th Type
      th Time
      th Actions
  tbody
    - @wonko_versions.each do |wonko_version|
      tr
        td = wonko_version.version
        td = click_to_edit wonko_version, path: route(:update, wonko_version), attribute: :type
        td = wonko_version.time_as_string
        td = bootstrap_button_group do
          = bootstrap_button_to 'Show', route(:show, wonko_version, user: wonko_version.user.username), :default if policy(wonko_version).show?
          = bootstrap_button_to 'Edit', route(:edit, wonko_version, user: wonko_version.user.username), :warning, icon: :edit if policy(wonko_version).edit?
          = link_to 'Destroy', route(:destroy, wonko_version, user: wonko_version.user.username), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' if policy(wonko_version).destroy?

app/views/wonko_versions/edit.html.slim
h1
  | Editing 
  = @wonko_version.version
= render 'form'

app/views/wonko_versions/index.html.slim
= render 'wonko_versions/table'
.btn-toolbar.list-toolbar[role="toolbar"]
  = bootstrap_button_group do
    = bootstrap_button_to 'New Wonko Version', route(:new, @wonko_file, WonkoVersion), :success, icon: :plus if policy(WonkoVersion).create?
  = paginate @wonko_versions

app/views/wonko_versions/list_of_variants.html.slim
.panel.panel-danger
  .panel-heading
    h3.panel-title
      b 404
      | : There doesn't seem to be anything here?
  .panel-body The requested version is available from these people though:
  .list-group
    - @wonko_versions.where(user: User.official_user).each do |version|
      a.list-group-item href="#{route :show, version, user: version.user.username}"
        = version.user.username
    - if @wur_enabled
      - @wonko_versions.where.not(user: User.official_user).each do |version|
        a.list-group-item href="#{route :show, version, user: version.user.username}"
          = version.user.username
    - elsif !@wonko_versions.where.not(user: User.official_user).empty?
      a.list-group-item.list-group-item-warning href="javascript:$('#wurEnabler').click()"
        | Enable the WUR the see others

app/views/wonko_versions/new.html.slim
h1 New Wonko Version
= render 'form'

h1 New Wonko Versions from file
= bootstrap_form_tag url: upload_version_path, multipart: true do |f|
  = f.alert_message "Please fix the errors below."
  = f.file_field :file, hide_label: true, multiple: true
javascript:
  $(function() {
    $('#_file')
            .attr('style', 'width:100%')
            .fileinput({
              previewFileType: 'text',
              allowedFileExtensions: ['json'],
              previewClass: 'bg-warning'
            });
  });

app/views/wonko_versions/show.html.slim
= form_tag 'javascript:return false;' do
  = bootstrap_button_group do
    = bootstrap_button_to 'Edit', route(:edit, @wonko_version, user: @wonko_version.user.username), :warning, icon: :edit if policy(@wonko_version).edit?
    = bootstrap_button_to 'Copy', route(:copy, @wonko_version, user: @wonko_version.user.username), :warning, icon: :duplicate if can_copy(@wonko_version)
    = bootstrap_button_to 'Go to Mine', route(:show, own(@wonko_version), user: current_user.username), :success if show_go_to_mine(@wonko_version)
    = bootstrap_button_to 'Download', api_v1_version_path(@wonko_file, @wonko_version), :success, icon: 'download-alt'
    = bootstrap_button_to 'Feed', route(:feed, @wonko_version), :default, icon: :list
    select.selectpicker[data-live-search="true"]
      - @wonko_version.wonko_file.wonkoversions.where(version: @wonko_version.version).pluck(:user_id).each do |user_id|
        option value="#{User.find(user_id).to_param}"
          = User.find(user_id).username

p
  strong Owner:
  span = link_to @wonko_version.user.username, route(:show, @wonko_version.user)
p
  strong Origin:
  span = @wonko_version.origin.to_html
p
  strong Version:
  span = @wonko_version.version
p
  strong Type:
  span = click_to_edit @wonko_version, url: route(:update, @wonko_version), attribute: :type
p
  strong Time:
  span = @wonko_version.time_as_string
p
  strong Requires:
  #requiresView
p
  strong Data:
  #dataView

javascript:
  var requiresEditor = new JSONEditor(document.getElementById('requiresView'),
  {
    mode: 'view',
    name: 'Dependencies'
  }, #{@wonko_version.requires.to_json.html_safe});
  var dataEditor = new JSONEditor(document.getElementById('dataView'),
  {
    mode: 'view',
    name: 'Resource Groups'
  }, #{@wonko_version.data.to_json.html_safe});
  $('select.selectpicker').on('change', function(evt) {
    var user = $(evt.target).val();
    if (user === 'official') {
      document.location.href = '#{route :show, @wonko_version}'
    } else {
      document.location.href = '#{route :show, @wonko_version}?user=' + user;
    }
  }).val('#{@wonko_version.user.username}');