config/routes.rb
def api_version_helper(version, mime, &block)
  version_str = "v#{version}"
  api_version module: version_str,
              path: { value: version_str },
              parameter: { name: :apiVersion, value: version_str },
              &block
  scope as: :header do
    api_version module: version_str, header: { name: :Accept, value: "#{mime};version=#{version}" }, &block
  end
end

Rails.application.routes.draw do
  controller :wiki, path: :wiki do
    get '/', action: :index, as: :wiki_index
    get ':page', action: :show, as: :wiki, page: %r{[^/]+}
  end

  controller :profile, path: :user do
    get '(:username)', action: :show, as: :profile
    get '(:username)/feed' => 'feed#user', as: :feed_profile
    get '(:username)/files', action: :files, as: :profile_files
    get '(:username)/versions', action: :versions, as: :profile_versions
    get '(:username)/brief_feed' => 'feed#brief_user', as: :brief_feed_profile
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    scope path: 'users' do
      match 'finish_signup' => 'users/registrations#finish_signup', via: [:get, :patch, :post], as: :finish_signup
      get 'accounts' => 'users/registrations#accounts', as: :user_accounts
      get 'auth/:provider/destroy' => 'users/omniauth_callbacks#destroy', as: :omniauth_unlink
      match 'reset_authentication_token' => 'users/registrations#reset_authentication_token',
            via: [:get, :patch, :post], as: :reset_authentication_token

      resources :uploaders do
        member do
          match 'reset_token', via: [:get, :patch, :post]
        end
      end
    end
  end

  authenticate :user, ->(user) { user.admin } do
    mount DjMon::Engine => 'dj_mon'
  end

  post 'upload_version' => 'wonko_versions#upload'

  resources :wonko_files, id: %r{[^/]+} do
    member do
      get 'feed' => 'feed#file'
      scope controller: 'wonko_files_transfer' do
        get 'transfer'
        post 'transfer'
        get 'accept_transfer'
        get 'reject_transfer'
        get 'cancel_transfer'
      end
    end

    resources :wonko_versions, id: %r{[^/]+} do
      member do
        get 'copy'
        get 'feed' => 'feed#version'
      end
    end
  end

  root 'home#index'
  get 'about' => 'home#about'
  get 'irc' => 'home#irc'

  namespace :api,
            format: true,
            constraints: { format: :json },
            defaults: { format: :json },
            wonko_file_id: %r{[^/]+},
            id: %r{[^/]+} do
    api_version_helper 1, 'application/wonkoweb-api' do
      scope controller: 'wonko_files' do
        root action: :index
        get 'index', action: :index, as: :index
        get ':id', action: :show, as: :file
        post action: :create, as: :create_file
        patch ':id', action: :update
      end
      scope path: ':wonko_file_id', controller: 'wonko_versions' do
        get ':id', action: :show, as: :version
        post action: :create, as: :create_version
        patch ':id', action: :update
      end
    end
  end

end

app/views/layouts/_feed.html.slim
li.media
  = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    = display_meta_tags site: 'WonkoWeb', reverse: true
    - cache do
      = raw analytical.head_prepend_javascript
      = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
      = javascript_include_tag 'application', 'data-turbolinks-track': true
      = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/4.1.3/jsoneditor.min.js', 'data-turbolinks-track': true
      = stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/4.1.3/jsoneditor.min.css', media: 'all', 'data-turbolinks-track': true
      = javascript_include_tag 'https://cdn.rawgit.com/kartik-v/bootstrap-fileinput/master/js/fileinput.js', 'data-turbolinks-track': true
      = stylesheet_link_tag 'https://cdn.rawgit.com/kartik-v/bootstrap-fileinput/master/css/fileinput.min.css', media: 'all', 'data-turbolinks-track': true
      = javascript_include_tag 'https://cdn.rawgit.com/truckingsim/Ajax-Bootstrap-Select/master/dist/js/ajax-bootstrap-select.min.js', 'data-turbolinks-track': true
      = stylesheet_link_tag 'https://cdn.rawgit.com/truckingsim/Ajax-Bootstrap-Select/master/dist/css/ajax-bootstrap-select.css', media: 'all', 'data-turbolinks-track': true
      = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.js', media: 'all', 'data-turbolinks-track': true
      = stylesheet_link_tag 'https://cdn.rawgit.com/richleland/pygments-css/master/github.css', media: 'all', 'data-turbolinks-track': true
      = raw analytical.head_append_javascript
    = csrf_meta_tags
    javascript:
      window.wurEnabled = #{@wur_enabled ? 'true' : 'false'};
      window.apiRootUrl = '#{api_v1_root_url}';
      ZeroClipboard.config({swfPath: 'https://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.swf' });
    coffee:
      setUrlQueryParameter = (key, value) ->
        url = new URI(document.location.href)
        url.setQuery key, value
        if document.location.href != url.href()
          document.location.href = url.href()
        return

      $(document).on 'page:change', ->
        clipboardClient = new ZeroClipboard($('.zeroclipboard'))
        $('#getUrlLink').on 'click', ->
          prompt 'Ctrl+C followed by Enter', window.apiRootUrl
          # TODO: this should be the path to some CDN
          return
        $('#wurEnabler').bootstrapSwitch
          labelText: 'WUR'
          state: window.wurEnabled
          onSwitchChange: (evt, state) ->
            if state == true
              bootbox.dialog
                message: 'This will enable the WonkoUserRepositories. This means you will see WonkoFiles and versions submitted by strangers that could potentially be malicious!'
                title: 'Enable the WUR?'
                buttons:
                  yes:
                    label: 'Yes'
                    className: 'btn-danger'
                    callback: ->
                      setUrlQueryParameter 'wur', true
                      return
                  no:
                    label: 'No'
                    className: 'btn-default'
                    callback: ->
                      $('#wurEnabler').click()
                      return
            else
              setUrlQueryParameter 'wur', false
            return
        return
  body data-spy="scroll" data-target=".scrollspy" data-no-turbolink="data-no-turbolink"
    = raw analytical.body_prepend_javascript
    - cache [current_user, (current_user ? current_user.notifications.size : 0)] do
      = navbar position: :static do
        = vertical do
          = link_to 'WonkoWeb', root_path
        = horizontal do
          = nav class: 'navbar-left' do
            li = link_to 'Get URL for MultiMC', '#', id: 'getUrlLink'
            li = link_to 'About', about_path
            li = link_to 'Wiki', wiki_index_path
          = form_tag '#', class: 'navbar-form navbar-left' do |f|
            .form-group
              input#wurEnabler.form-control type="checkbox"
          = nav class: 'navbar-right' do
            - if user_signed_in?
              = render 'application/notifications'
              li = link_to 'Edit account', edit_user_registration_path
              li = link_to 'Sign out', destroy_user_session_path, method: :delete
            - else
              li = link_to 'Sign in', new_user_session_path
              li = link_to 'Sign up', new_user_registration_path

    .container
      - if not devise_controller?
        = render_breadcrumbs builder: BootstrapBreadcrumbsBuilder
      = bootstrap_flash
      = yield

    footer.navbar.navbar-default.navbar-fixed-bottom
      .container
        div style="height: 15px;"
        center.footer-contents
          ' © 2015 Jan Dalheimer
          = gi_icon :asterisk, size: :sm
          = link_to 'Contact', about_path + '#contact'
    - if Rails.env.production?
      javascript:
        var pkBaseURL = (("https:" == document.location.protocol) ? "https://#{ENV['WONKOWEB_PIWIK_HOST']}/" : "http://#{ENV['WONKOWEB_PIWIK_HOST']}/");
        document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
      javascript:
        try {
          var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 1);
          piwikTracker.trackPageView();
          piwikTracker.enableLinkTracking();
        } catch( err ) {}
    = raw analytical.body_append_javascript